/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WholesaleRouteImport } from './routes/wholesale'
import { Route as StockRouteImport } from './routes/stock'
import { Route as StaffRouteImport } from './routes/staff'
import { Route as RetailRouteImport } from './routes/retail'
import { Route as IndexRouteImport } from './routes/index'

const WholesaleRoute = WholesaleRouteImport.update({
  id: '/wholesale',
  path: '/wholesale',
  getParentRoute: () => rootRouteImport,
} as any)
const StockRoute = StockRouteImport.update({
  id: '/stock',
  path: '/stock',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffRoute = StaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const RetailRoute = RetailRouteImport.update({
  id: '/retail',
  path: '/retail',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/retail': typeof RetailRoute
  '/staff': typeof StaffRoute
  '/stock': typeof StockRoute
  '/wholesale': typeof WholesaleRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/retail': typeof RetailRoute
  '/staff': typeof StaffRoute
  '/stock': typeof StockRoute
  '/wholesale': typeof WholesaleRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/retail': typeof RetailRoute
  '/staff': typeof StaffRoute
  '/stock': typeof StockRoute
  '/wholesale': typeof WholesaleRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/retail' | '/staff' | '/stock' | '/wholesale'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/retail' | '/staff' | '/stock' | '/wholesale'
  id: '__root__' | '/' | '/retail' | '/staff' | '/stock' | '/wholesale'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RetailRoute: typeof RetailRoute
  StaffRoute: typeof StaffRoute
  StockRoute: typeof StockRoute
  WholesaleRoute: typeof WholesaleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wholesale': {
      id: '/wholesale'
      path: '/wholesale'
      fullPath: '/wholesale'
      preLoaderRoute: typeof WholesaleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stock': {
      id: '/stock'
      path: '/stock'
      fullPath: '/stock'
      preLoaderRoute: typeof StockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff': {
      id: '/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof StaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/retail': {
      id: '/retail'
      path: '/retail'
      fullPath: '/retail'
      preLoaderRoute: typeof RetailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RetailRoute: RetailRoute,
  StaffRoute: StaffRoute,
  StockRoute: StockRoute,
  WholesaleRoute: WholesaleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
